"""Workspace state detection.

Each check answers "do we need to run the corresponding step?" so the
build command can stay idempotent across repeated invocations.

NXP path (manifest/branch/SHA consistency)
------------------------------------------

Google ``repo`` tracks the active manifest inside ``.repo/manifest.xml``
(a generated include) and the active branch in ``.repo/manifests.git/config``.
When the user flips manifests (scarthgap -> walnascar, or just
imx-A.B.C-X.Y.Z to a newer version), ``.repo/`` still looks
"initialized" and ``sources/poky`` still exists, but the on-disk SHAs
belong to the old manifest. Without a mismatch check we skip ``repo
sync`` and silently build against the wrong tree.

TI path
-------

The TI BSP is populated by ``oe-layertool-setup.sh`` (a shell wrapper
in ``varigit/oe-layersetup``). There is no ``.repo/``; the script
clones layers directly into ``sources/`` against pinned SHAs read
from a ``processor-sdk-...-config_var<N>.txt`` file. We track the
last-applied config name in ``ti/conf/active-config.txt`` so the
config-drift check fires when the user flips configs. SHA-level
drift detection is out of scope for the TI path - re-running the
script is cheap, and ``check_ti_layertool_config_consistency``
covers the user-facing axis.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import xml.dom.minidom
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from bspctl.config import BuildConfig

# -- helpers (used by detect()) ------------------------------------------------


_HEX40_RE = re.compile(r"^[0-9a-f]{40}$")
_MANIFESTS_MERGE_RE = re.compile(r"^\s*merge\s*=\s*refs/heads/(\S+)\s*$", re.MULTILINE)


def read_repo_manifest_include(repo_dir: Path) -> str | None:
    """Return the basename of the manifest included by ``.repo/manifest.xml``.

    ``.repo/manifest.xml`` is generated by ``repo init`` and contains a
    single ``<include name="..."/>`` pointing at the real manifest under
    ``.repo/manifests/``. Returns ``None`` if the file is missing, empty,
    or does not contain an include element.
    """
    mfx = repo_dir / "manifest.xml"
    if not mfx.is_file():
        return None
    try:
        doc = xml.dom.minidom.parse(str(mfx))
    except (OSError, xml.parsers.expat.ExpatError):
        return None
    includes = doc.getElementsByTagName("include")
    if not includes:
        return None
    name = includes[0].getAttribute("name")
    return name or None


def read_repo_manifests_branch(repo_dir: Path) -> str | None:
    """Return the branch ``.repo/manifests.git`` is tracking.

    repo-tool writes the active branch as ``merge = refs/heads/<branch>``
    in ``.repo/manifests.git/config``. Returns ``None`` if that file is
    missing or does not contain a merge line.
    """
    cfg = repo_dir / "manifests.git" / "config"
    if not cfg.is_file():
        return None
    try:
        text = cfg.read_text()
    except OSError:
        return None
    m = _MANIFESTS_MERGE_RE.search(text)
    return m.group(1) if m else None


def parse_manifest_pins(manifest_path: Path) -> list[tuple[str, str]]:
    """Return ``(sources/<path>, expected_sha)`` for projects pinned to a SHA.

    Manifest entries using branch names, tags, or ``refs/tags/...`` are
    skipped because on-disk ``HEAD`` after a sync is a SHA either way,
    and we cannot assert equality without resolving the ref.
    """
    if not manifest_path.is_file():
        return []
    try:
        doc = xml.dom.minidom.parse(str(manifest_path))
    except (OSError, xml.parsers.expat.ExpatError):
        return []
    pins: list[tuple[str, str]] = []
    for proj in doc.getElementsByTagName("project"):
        path = proj.getAttribute("path")
        rev = proj.getAttribute("revision")
        if path and rev and _HEX40_RE.match(rev):
            pins.append((path, rev))
    return pins


def _head_sha(checkout: Path) -> str | None:
    """Return on-disk ``HEAD`` SHA for a git checkout, or None on error."""
    if not (checkout / ".git").exists():
        return None
    try:
        out = subprocess.run(
            ["git", "-C", str(checkout), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    sha = out.stdout.strip()
    return sha if _HEX40_RE.match(sha) else None


def find_sha_drift(workspace: Path, pins: list[tuple[str, str]]) -> list[tuple[str, str, str]]:
    """Return ``(path, expected, actual)`` triples where on-disk HEAD disagrees."""
    drift: list[tuple[str, str, str]] = []
    for path, expected in pins:
        actual = _head_sha(workspace / path)
        if actual is None:
            # Not cloned yet, or unreadable -- a fresh sync covers it.
            continue
        if actual != expected:
            drift.append((path, expected, actual))
    return drift


# -- state -------------------------------------------------------------------


@dataclass(frozen=True)
class WorkspaceState:
    """Snapshot of what already exists in the workspace.

    Fields prefixed by ``repo_`` are NXP-specific (Google ``repo`` is
    not used on the TI side); they default to ``None`` / ``False`` /
    ``()`` for TI and the per-BSP doctor checks read them only when
    ``bsp_family == "nxp"``.
    """

    bsp_family: Literal["nxp", "ti"]
    repo_initialized: bool
    sources_populated: bool
    build_dir_exists: bool
    bblayers_present: bool
    kas_yaml_present: bool
    forks_linux_imx: bool
    cache_dirs_ok: bool
    # Manifest/branch consistency (NXP only; ``None`` on TI)
    repo_manifest_include: str | None
    repo_manifests_branch: str | None
    requested_manifest: str
    requested_branch: str
    sha_drift: tuple[tuple[str, str, str], ...] = field(default_factory=tuple)

    @property
    def repo_broken(self) -> bool:
        """`.repo/` exists but we cannot read the tracked manifest. NXP only.

        TI has no `.repo/` semantics (the layertool clones bitbake et al.
        directly into ``ti/sources/``), so the manifest-include /
        manifests-branch fields are intentionally ``None`` and must not
        flag the workspace as broken.
        """
        if self.bsp_family != "nxp":
            return False
        return self.repo_initialized and self.repo_manifest_include is None

    @property
    def manifest_mismatch(self) -> bool:
        """User-requested manifest differs from `.repo/manifest.xml` include."""
        return self.repo_manifest_include is not None and self.repo_manifest_include != self.requested_manifest

    @property
    def branch_mismatch(self) -> bool:
        """User-requested branch differs from `.repo/manifests.git` tracking."""
        return self.repo_manifests_branch is not None and self.repo_manifests_branch != self.requested_branch

    @property
    def needs_full_reinit(self) -> bool:
        """Caller must re-run `repo init` (not just `repo sync`)."""
        return self.repo_broken or self.manifest_mismatch or self.branch_mismatch

    @property
    def needs_repo_sync(self) -> bool:
        if not (self.repo_initialized and self.sources_populated):
            return True
        return self.needs_full_reinit or bool(self.sha_drift)

    @property
    def needs_setup_env(self) -> bool:
        # bblayers.conf rendered against an old manifest is stale across a
        # reinit; force a regenerate when the sync will reinit `.repo/`.
        if self.needs_full_reinit:
            return True
        return not self.bblayers_present

    @property
    def needs_gen_kas(self) -> bool:
        return not self.kas_yaml_present


def detect(cfg: BuildConfig) -> WorkspaceState:
    """Inspect the workspace and return a state snapshot.

    Does not mutate anything; safe to call repeatedly. Branches on
    ``cfg.bsp_family``: NXP reads ``.repo/`` and parses the manifest
    XML; TI looks for the oe-layertool tree and the populated
    ``sources/oe-core/`` checkout.
    """
    if cfg.bsp_family == "ti":
        return _detect_ti(cfg)
    return _detect_nxp(cfg)


def _detect_nxp(cfg: BuildConfig) -> WorkspaceState:
    ws = cfg.workspace
    nxp = ws / "nxp"
    repo_dir = nxp / ".repo"
    sources_dir = nxp / "sources"
    # A single path-only heuristic: if sources/poky/oe-init-build-env exists
    # after a repo sync, the workspace is fully populated.
    sources_populated = (sources_dir / "poky" / "oe-init-build-env").is_file()

    include = read_repo_manifest_include(repo_dir) if repo_dir.is_dir() else None
    branch = read_repo_manifests_branch(repo_dir) if repo_dir.is_dir() else None
    # SHA drift check only makes sense once we have on-disk sources AND a
    # target manifest we can parse. Skip it otherwise -- a reinit is
    # already implied by other signals.
    drift: tuple[tuple[str, str, str], ...] = ()
    if sources_populated and cfg.manifest_path.is_file():
        pins = parse_manifest_pins(cfg.manifest_path)
        drift = tuple(find_sha_drift(nxp, pins))

    return WorkspaceState(
        bsp_family="nxp",
        repo_initialized=repo_dir.is_dir(),
        sources_populated=sources_populated,
        build_dir_exists=(nxp / "build").is_dir(),
        bblayers_present=cfg.bblayers_conf.is_file(),
        kas_yaml_present=cfg.kas_yaml.is_file() and cfg.kas_yaml.stat().st_size > 200,
        forks_linux_imx=(nxp / "forks" / "linux-imx").is_dir(),
        cache_dirs_ok=_cache_dirs_ok(),
        repo_manifest_include=include,
        repo_manifests_branch=branch,
        requested_manifest=cfg.manifest,
        requested_branch=cfg.repo_branch,
        sha_drift=drift,
    )


def _detect_ti(cfg: BuildConfig) -> WorkspaceState:
    """TI workspace state.

    ``repo_initialized`` is True when the oe-layertool clone is on
    disk (``ti/oe-layertool/oe-layertool-setup.sh`` exists);
    ``sources_populated`` is True when the script has run at least
    once (``ti/sources/oe-core/oe-init-build-env`` exists). The
    NXP-specific manifest-include / branch-tracking fields are
    ``None`` and feed False through the mismatch properties so
    ``needs_full_reinit`` does not fire on the TI side.
    """
    ws = cfg.workspace
    ti = ws / "ti"
    layertool_script = ti / "oe-layertool" / "oe-layertool-setup.sh"
    sources_populated = (ti / "sources" / "oe-core" / "oe-init-build-env").is_file()
    return WorkspaceState(
        bsp_family="ti",
        repo_initialized=layertool_script.is_file(),
        sources_populated=sources_populated,
        build_dir_exists=(ti / "build").is_dir(),
        bblayers_present=cfg.bblayers_conf.is_file(),
        kas_yaml_present=cfg.kas_yaml.is_file() and cfg.kas_yaml.stat().st_size > 200,
        forks_linux_imx=False,  # NXP-only; always False on TI
        cache_dirs_ok=_cache_dirs_ok(),
        repo_manifest_include=None,
        repo_manifests_branch=None,
        requested_manifest=cfg.manifest,
        requested_branch=cfg.repo_branch,
        sha_drift=(),
    )


def _cache_dirs_ok() -> bool:
    """All three tiered cache paths exist and are writable."""
    import os

    paths = [
        Path("/mnt/BACKUP_ROOT/yocto-cache/sstate"),
        Path("/mnt/JETM_SATA_9.1T/yocto-cache/downloads"),
    ]
    for p in paths:
        if not p.is_dir() or not os.access(p, os.W_OK):
            return False
    return True


def ensure_tools(cfg: BuildConfig) -> list[str]:
    """Return a list of missing host tools.

    An empty list means every required binary is on PATH. Branches on
    ``cfg.bsp_family``: NXP requires ``repo``, TI requires ``git``
    (oe-layertool-setup.sh shells out to it).
    """
    if cfg.bsp_family == "ti":
        required = ["git", "kas-container", "docker", "python3"]
    else:
        required = ["repo", "kas-container", "docker", "python3"]
    return [tool for tool in required if shutil.which(tool) is None]
